#lang racket

(require "infrabel.rkt")

(define infrabel-listener (tcp-listen infrabel-port))
(define-values (in out) (tcp-accept infrabel-listener))

(define infrabel-evt-listener (tcp-listen (+ infrabel-port 1)))
(define-values (evt-in evt-out) (tcp-accept infrabel-evt-listener))

(define (push-evt . evts)
  (writeln evts)
  (writeln evts evt-out)
  (flush-output evt-out))

(define (run-server (input "../input.txt"))
  (infrabel-init input)
  (define evt-handler (thread (lambda ()
                                (let loop ()
                                  (run push-evt)
                                  (loop)))))
  (let loop ((msg (begin (displayln "server activated") (read in))))
    (when (eof-object? msg)
      (close-input-port in)
      (close-output-port out)
      (tcp-close infrabel-listener)
      (displayln "Infrabel quit successfully.")
      (exit))
    ;(display "Infrabel request received: ")
    ;(displayln msg)
    (case msg
      ((get-loco-speed)
       (writeln (get-loco-speed (read in)) out))
      ; (send (get-loco (read in)) get-speed))
      ((set-loco-speed)
       (set-loco-speed! (read in) (read in)))
      ; (send (get-loco (read in)) set-speed (read in)))
      ((get-loco-position)
       (writeln (get-loco-position (read in)) out))
       ; (send (get-loco (read in)) get-position))
       ;((change-loco-position)
       ; (change-loco-position! (read in
       ;(send (get-loco (read in)) set-position (read in)))
      ;((change-loco-direction)
       ;(send (get-loco (read in)) change-direction))
      ;((get-detection-block-status)
       ;(send (get-detection-block (read in)) get-status))
      ((get-current-switch-position)
       (writeln (send (get-current-switch-position (read in)) get-id) out))
      ((get-alternative-switch-position)
       (writeln (send (get-alternative-switch-position (read in)) get-id) out))
      ((change-switch-position)
       (change-switch-position! (read in)))
      (else (error "Unknown request: " msg)))
  (flush-output out)
    (loop (read in))))

(run-server)

